apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend-user
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-feed
        image: docker.io/adwoabrems/udagram-api-user:v3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
        
